language: python
python:
  - "3.8.10"  # Choose the Python version you want to test against

install:
  - pip install -r requirements.txt  # Install project dependencies

before_script:
  - git clone https://github.com/umangpurwar03/MLops-Basic-Project.git # Clone your GitHub repository
  - mv MLops-Basic-Project/data data # Move the data directory into your project's root
  # If the data directory has a different name, replace 'YourRepository' with the actual repository name

script:
  - python -m unittest unit_test2 # Run your unit tests
